ls /home/omega3/omega_project/genomon/ACC/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam  > normal_panel/list_normal_sample_ACC.txt
ls /home/omega3/omega_project/genomon/BLCA/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_BLCA.txt
ls /home/omega3/omega_project/genomon/BRCA/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_BRCA.txt
ls /home/omega3/omega_project/genomon/CESC/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_CESC.txt
ls /home/omega3/omega_project/genomon/CHOL/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_CHOL.txt
ls /home/omega3/omega_project/genomon/COAD/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_COAD.txt
ls /home/omega3/omega_project/genomon/DLBC/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_DLBC.txt
ls /home/omega3/omega_project/genomon/ESCA/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_ESCA.txt
ls /home/omega3/omega_project/genomon/GBM/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam  > normal_panel/list_normal_sample_GBM.txt
ls /home/omega3/omega_project/genomon/HNSC/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_HNSC.txt
ls /home/omega3/omega_project/genomon/KICH/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_KICH.txt
ls /home/omega3/omega_project/genomon/KIRC/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_KIRC.txt
ls /home/omega3/omega_project/genomon/KIRP/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_KIRP.txt
ls /home/omega3/omega_project/genomon/LAML/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_LAML.txt
ls /home/omega3/omega_project/genomon/LGG/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam  > normal_panel/list_normal_sample_LGG.txt
ls /home/omega3/omega_project/genomon/LIHC/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_LIHC.txt
ls /home/omega3/omega_project/genomon/LUAD/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_LUAD.txt
ls /home/omega3/omega_project/genomon/LUSC/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_LUSC.txt
ls /home/omega3/omega_project/genomon/MESO/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_MESO.txt
ls /home/omega3/omega_project/genomon/OV/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam   > normal_panel/list_normal_sample_OV.txt
ls /home/omega3/omega_project/genomon/PAAD/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_PAAD.txt
ls /home/omega3/omega_project/genomon/PCPG/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_PCPG.txt
ls /home/omega3/omega_project/genomon/PRAD/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_PRAD.txt
ls /home/omega3/omega_project/genomon/READ/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_READ.txt
ls /home/omega3/omega_project/genomon/SARC/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_SARC.txt
ls /home/omega3/omega_project/genomon/SKCM/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_SKCM.txt
ls /home/omega3/omega_project/genomon/STAD/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_STAD.txt
ls /home/omega3/omega_project/genomon/TGCT/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_TGCT.txt
ls /home/omega3/omega_project/genomon/THCA/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_THCA.txt
ls /home/omega3/omega_project/genomon/THYM/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_THYM.txt
ls /home/omega3/omega_project/genomon/UCEC/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam > normal_panel/list_normal_sample_UCEC.txt
ls /home/omega3/omega_project/genomon/UCS/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam  > normal_panel/list_normal_sample_UCS.txt
ls /home/omega3/omega_project/genomon/UVM/bam/TCGA-*-1?/TCGA-*-1?.markdup.bam  > normal_panel/list_normal_sample_UVM.txt


